model:
    arch: fcn8s
data:
    dataset: camvid
    train_split: train
    val_split: val
    img_rows: 846
    img_cols: 271
    path: E:/Autopilot/datasets/ROAD_LINES_846x271/
    sbd_path: E:/Autopilot/datasets/ROAD_LINES_846x271/
training:
    train_iters: 300000
    batch_size: 1
    val_interval: 1000
    n_workers: 1
    print_interval: 2
    optimizer:
        name: 'sgd'
        lr: 1.0e-10
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume: fcn8s_pascal_best_model.pkl
